"""Recommendation Response and Policy Guardrail Validator."""

import logging
from schemas.recommendation import RecommendationResponse, TeachingStrategy, HintLevelEnum

logger = logging.getLogger(__name__)


class RecommendationValidator:
    """Enforces schema completeness and policy safety guardrails on generated responses."""

    def validate(
        self,
        response: RecommendationResponse,
        strategy: TeachingStrategy
    ) -> RecommendationResponse:
        """Validates that the generated recommendation respects policy constraints.

        Args:
            response: RecommendationResponse object generated by the Generator.
            strategy: Active TeachingStrategy governing educational rules.

        Returns:
            Validated (and cleaned if necessary) RecommendationResponse.
        """
        hint_level = strategy.hint_level

        # 1. Enforce Code Leakage Guardrail:
        # If strategy forbids code (No Hint, Concept, Guided, Pseudocode), set code and complexity to None
        if not strategy.allow_code and hint_level != HintLevelEnum.FULL_SOLUTION:
            if response.code is not None:
                logger.warning(
                    "POLICY VIOLATION DETECTED: Code present in response for level '%s'. Sanitizing code field.",
                    hint_level.value
                )
                response.code = None

            if response.complexity is not None:
                logger.warning(
                    "POLICY VIOLATION DETECTED: Complexity info present for level '%s'. Sanitizing complexity field.",
                    hint_level.value
                )
                response.complexity = None

        # 2. Enforce Mandatory Reflection Question:
        if strategy.require_reflection_question and not (response.reflection_question or "").strip():
            logger.warning("Missing reflection question for hint level '%s'. Inserting default reflection prompt.", hint_level.value)
            response.reflection_question = "What is the key assumption behind your current problem solving approach?"

        # 3. Ensure required non-empty text fields
        if not (response.message or "").strip():
            response.message = "Focus on breaking down your algorithm step-by-step."

        if not (response.next_step or "").strip():
            response.next_step = "Review your code logic against simple test inputs."

        if not (response.encouragement or "").strip():
            response.encouragement = "Keep going! Active practice builds deep intuition."

        logger.info("RecommendationValidator successfully passed guardrail checks for level '%s'", hint_level.value)
        return response
